Repository FEIProjectTeam/asos, pull requests merged in 2024-12, with the labels that each got.

#18 Create post modal
  Dockerfile
  docker-compose.yml
  project/forms.py
  project/migrations/0001_initial.py
  project/migrations/0002_like_unique_like_per_post_and_more.py
  project/templates/base.html
  project/templates/post/createPost.html
  project/urls.py
  project/views.py
Labels: FrontEnd, BackEnd

#23 22-profile-settings-page
  project/forms.py
  project/templates/base.html
  project/templates/settings.html
  project/templates/settingsPass.html
  project/templates/settingsProfile.html
  project/urls.py
  project/views.py
Labels: New feature, FrontEnd, BackEnd

#30 changed Create post file selector to accept multiple files.
  project/forms.py
  project/templates/post/createPost.html
  project/templates/post/post_detail.html
  project/views.py
Labels: bug, FrontEnd, BackEnd

#21 Dashboard page
  project/settings.py
  project/static/style.css
  project/templates/base.html
  project/templates/home.html
  project/templates/post/post_create.html
  project/templates/post/post_list.html
  project/urls.py
  project/views.py
Labels: New feature, FrontEnd, BackEnd

#33 changed file selector to scroll in Create post
  project/forms.py
  project/templates/post/post_create.html
Labels: bug, FrontEnd

#35 Post list fixes
  .gitignore
  project/static/style.css
  project/templates/home.html
  project/templates/post/post_list.html
Labels: bug, FrontEnd
